name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd Portfolio
          git checkout origin production
          git pull origin production
          npm install
          npm run build  # Add this line to build the Next.js app
          # Check if the app is running and stop it if it is
          if pm2 list | grep -q "app-portfolio"; then
            pm2 stop app-portfolio
          fi
          pm2 start npm --name "app-portfolio" -- run start -- -H 0.0.0.0 -p 3000
          pm2 save
          EOF
